# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.cache/wt} [current_project]
set_property parent.project_path {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/Oled_Display.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/audio_capture.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/beatdetection.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/beaten_high_score_interface.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/bimpy.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/bitreverse.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/butterfly.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/clock_divider.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/convround.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/display_score.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/fftmain.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/fftstage.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/game_start_interface.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/hwbfly.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/instr_press_centre.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/instr_press_down.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/instr_press_left.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/instr_press_right.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/instr_press_up.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/laststage.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/longbimpy.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/qtrstage.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/random_shape_generator.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/random_x_generator1.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/random_x_generator2.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/random_x_generator3.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/random_x_generator4.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/slow_clock.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/try_again_interface.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/ui.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/welcome_interface.v}
  {C:/Users/leowk/nus/EE2026 Vivado/project_improvement/project_improvement.srcs/sources_1/new/main.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/.shortcut-targets-by-id/13VWQVSxigkPnLWfHfWfAyjPygEYu7_-z/Y2S2/EE2026/Lab/Basys3_Master.xdc
set_property used_in_implementation false [get_files G:/.shortcut-targets-by-id/13VWQVSxigkPnLWfHfWfAyjPygEYu7_-z/Y2S2/EE2026/Lab/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
